# Automatically generated build file. Do not edit.
COMPONENT_INCLUDES += $(PROJECT_PATH)/components/ESP32_VL53L0X $(PROJECT_PATH)/components/ESP32_VL53L0X/core/inc $(PROJECT_PATH)/components/ESP32_VL53L0X/platform/inc
COMPONENT_LDFLAGS += -L$(BUILD_DIR_BASE)/ESP32_VL53L0X -lESP32_VL53L0X
COMPONENT_LINKER_DEPS += 
COMPONENT_SUBMODULES += 
COMPONENT_LIBRARIES += ESP32_VL53L0X
COMPONENT_LDFRAGMENTS += 
component-ESP32_VL53L0X-build: 
