#pragma once

#define SDA_PIN GPIO_NUM_21
#define SCL_PIN GPIO_NUM_22

#define IR_DECODER_PIN GPIO_NUM_25
#define IR_PHOTODIODE1_PIN ADC1_CHANNEL_0
#define IR_PHOTODIODE2_PIN ADC1_CHANNEL_3
#define IR_LED1_PIN GPIO_NUM_32
