#pragma once

#define SDA_PIN GPIO_NUM_21
#define SCL_PIN GPIO_NUM_22

#define IR_DECODER_PIN GPIO_NUM_25
#define IR_PHOTODIODE1_PIN ADC1_CHANNEL_0
#define IR_PHOTODIODE2_PIN ADC1_CHANNEL_3
#define IR_LED_PIN GPIO_NUM_32

#define MOTOR_1_STEP_PIN GPIO_NUM_12
#define MOTOR_2_STEP_PIN GPIO_NUM_2
#define MOTOR_1_DIRECTION_PIN GPIO_NUM_13
#define MOTOR_2_DIRECTION_PIN GPIO_NUM_4

#define MOTOR_MICROSTEP_1 GPIO_NUM_26
#define MOTOR_MICROSTEP_2 GPIO_NUM_27
#define MOTOR_MICROSTEP_3 GPIO_NUM_14
