#pragma once

//#define PRINT_DURARIONS
//#define PRINT_ACCEL
//#define PRINT_COMPASS
//#define PRINT_PROXIMITY
//#define PRINT_PROXIMITY_ALL
//#define PRINT_TOF_SENSOR
//#define PRINT_MOTION_VISUAL
//#define PRINT_VOLTAGE
//#define DEBUG_OBJECT_SEARCH
//#define DEBUG_SERVO_AUTO_ADJUST
#define PRINT_WIFI
#define DEBUG_BADLY_PROGRAMMED_ALGORITM